### ISSUE TITLE
The Nuxt3 Stackblitz app fails with 500 error

### ISSUE THREAD

**Issue by admrid** [yikoyu/vuetify-pro-tiptap#380]
[Nuxt3 Stackblitz](https://stackblitz.com/~/github.com/yikoyu/vuetify-pro-tiptap-demo/tree/nuxt) does not load the example app preview as it fails with a 500:

 ERROR  [nuxt] [request error] [unhandled] [500] terminated
  at pA.onAborted (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:93:330807)  
  at pA.emit (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:30:10899)  
  at pA.terminate (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:93:318189)  
  at Object.onError (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:93:333385)  
  at _Request.onError (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:93:120945)  
  at errorRequest (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:93:312118)  
  at Socket.onSocketClose (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:93:299703)  
  at Socket.emit (https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:30:10899)  
  at https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:285:3666  
  at https://vuetifyprotiptapdemo-ffek-y39gpsfg.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:198822

**Comment by yikoyu** [comment]
Nuxt3 Stackblitz is working properly
